apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name:  build-task
spec:
  inputs:
    resources:
      - name: source-repo
        type: git

  steps:
    - name: build
      image: golang:alpine
      workingDir: /workspace/source-repo
      command:
        - go
      args:
        - "build"
        - "."
